/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parcialdosestructura;

/**
 *
 * @author URIEL MAURICIO
 */
public class MenuParcial extends javax.swing.JFrame {

    // ── Lógica directa (sin controlador intermedio) ───────────────────────────
    private final ListaDoble         lista     = new ListaDoble();
    private final SimuladorSensores  simulador = new SimuladorSensores();
    private javax.swing.Timer        timerSensores;

    /**
     * Creates new form MenuParcial
     */
    public MenuParcial() {
        initComponents();
        configurarVentana();
        mostrar("Sistema iniciado. " + lista.size + " registros cargados en memoria.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  CONFIGURACIÓN INICIAL (se llama una sola vez desde el constructor)
    // ─────────────────────────────────────────────────────────────────────────

    /** Ajustes generales de la ventana. */
    private void configurarVentana() {
        setTitle("Sistema de Gestión de Alertas IoT");
        setSize(950, 650);
        setLocationRelativeTo(null); // centrar en pantalla

        // Timer: dispara un ciclo de simulación cada 1.5 segundos
        timerSensores = new javax.swing.Timer(1500, e -> {
            String[] lectura  = simulador.generarLectura();
            String   sensorId = lectura[0];
            String   tipo     = lectura[1];
            float    valor    = Float.parseFloat(lectura[2]);
            String   resultado = lista.validarEInsertar(sensorId, tipo, valor);
            mostrar(String.format("Auto → %s (%s): %.2f → %s", sensorId, tipo, valor, resultado));
        });
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  MÉTODOS AUXILIARES DE INTERFAZ
    // ─────────────────────────────────────────────────────────────────────────

    /** Muestra un mensaje en el área de texto y hace scroll al final. */
    private void mostrar(String mensaje) {
        JTextArea.append(mensaje + "\n");
        JTextArea.setCaretPosition(JTextArea.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnConsultarId = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSensorBuscar = new javax.swing.JTextField();
        btnFiltrarSensor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUmbral = new javax.swing.JTextField();
        btnEliminarUmbral = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSensorId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnListarInv = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnPeligroVib = new javax.swing.JButton();
        btnCondensacion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Operación: ");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnConsultarId.setText("🔍 Consultar por ID ");
        btnConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdActionPerformed(evt);
            }
        });

        btnRevisar.setText("✅ Marcar Revisada ");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });

        btnEliminar.setText("❌ Eliminar por ID ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar Sensor ID: ");

        txtSensorBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSensorBuscarActionPerformed(evt);
            }
        });

        btnFiltrarSensor.setText("🔎 Filtrar Sensor ");
        btnFiltrarSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarSensorActionPerformed(evt);
            }
        });

        jLabel3.setText("Umbral Temp (°C): ");

        txtUmbral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmbralActionPerformed(evt);
            }
        });

        btnEliminarUmbral.setText("🌡 Eliminar Temp ID");
        btnEliminarUmbral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUmbralActionPerformed(evt);
            }
        });

        btnSimular.setText("▶ Iniciar Simulación ");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        btnDetener.setText("⏹ Detener Simulación ");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        jLabel4.setText("Sensor ID:");

        txtSensorId.setText("SENS-1");
        txtSensorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSensorIdActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperatura", "Humedad", "Vibración" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor:");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar Manual ");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar Todas ");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnListarInv.setText("Listar Inverso ");
        btnListarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarInvActionPerformed(evt);
            }
        });

        btnReportes.setText("📊 Reportes ");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnPeligroVib.setText("⚠ Peligro Vibración ");
        btnPeligroVib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeligroVibActionPerformed(evt);
            }
        });

        btnCondensacion.setText("💧 Riesgo Condensación ");
        btnCondensacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondensacionActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Pantalla ");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        JTextArea.setEditable(false);
        JTextArea.setColumns(20);
        JTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        JTextArea.setRows(5);
        jScrollPane1.setViewportView(JTextArea);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnSimular)
                        .addGap(33, 33, 33)
                        .addComponent(btnDetener))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSensorId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListar)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarInv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeligroVib)
                        .addGap(18, 18, 18)
                        .addComponent(btnCondensacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnConsultarId)
                            .addComponent(btnRevisar))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(btnEliminarUmbral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSensorBuscar)
                        .addComponent(btnFiltrarSensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUmbral)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimular)
                    .addComponent(btnDetener))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnListarInv)
                    .addComponent(btnReportes)
                    .addComponent(btnPeligroVib)
                    .addComponent(btnCondensacion)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarId)
                        .addGap(18, 18, 18)
                        .addComponent(btnRevisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarUmbral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSensorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrarSensor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUmbral, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // No se necesita lógica adicional al cambiar tipo de sensor
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // No se necesita lógica adicional al seleccionar tipo de sensor
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // Al presionar Enter en el campo ID, ejecuta la consulta
        btnConsultarIdActionPerformed(evt);
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnListarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarInvActionPerformed
        // CONSULTAR: Listar todas las alertas en orden inverso (de cola a cabeza)
        mostrar("--- TODAS LAS ALERTAS (INVERSO) ---");
        mostrar(lista.listarTodas(true));
    }//GEN-LAST:event_btnListarInvActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // CONSULTAR: Listar todas las alertas en orden cronológico (cabeza a cola)
        mostrar("--- TODAS LAS ALERTAS ---");
        mostrar(lista.listarTodas(false));
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // Genera reportes estadísticos (promedios, conteo por prioridad, sensor más problemático)
        mostrar(lista.generarReportes());
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnPeligroVibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeligroVibActionPerformed
        // CONSULTAR: Filtra alertas de vibración con valor > 7.1 mm/s (peligro)
        mostrar("--- PELIGRO VIBRACIÓN (> 7.1 mm/s) ---");
        mostrar(lista.listarVibracionPeligro());
    }//GEN-LAST:event_btnPeligroVibActionPerformed

    private void btnCondensacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondensacionActionPerformed
        // CONSULTAR: Filtra alertas de humedad con riesgo de condensación (> 80%)
        mostrar("--- RIESGO DE CONDENSACIÓN (Humedad > 80%) ---");
        mostrar(lista.consultarHistorialHumedadCondensacion());
    }//GEN-LAST:event_btnCondensacionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpia el área de texto
        JTextArea.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // CREAR: Inserción manual de una alerta llamando directamente a ListaDoble
        try {
            String sensorId = txtSensorId.getText();
            String tipo     = (String) cmbTipo.getSelectedItem();
            float  valor    = Float.parseFloat(txtValor.getText().trim());
            String resultado = lista.validarEInsertar(sensorId, tipo, valor);
            mostrar("Manual: " + resultado);
        } catch (NumberFormatException e) {
            mostrar("Error: el valor ingresado no es un número válido.");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // Al presionar Enter en el campo valor, ejecuta la inserción
        btnInsertarActionPerformed(evt);
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtSensorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSensorIdActionPerformed
        // No se necesita acción al presionar Enter en Sensor ID
    }//GEN-LAST:event_txtSensorIdActionPerformed

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        // Inicia la simulación automática de sensores con el Timer
        timerSensores.start();
        mostrar("--- SIMULACIÓN INICIADA ---");
    }//GEN-LAST:event_btnSimularActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // Detiene la simulación automática de sensores
        timerSensores.stop();
        mostrar("--- SIMULACIÓN DETENIDA ---");
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void btnConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdActionPerformed
        // CONSULTAR: Busca una alerta específica por su ID en la lista doble
        String idTexto = txtId.getText();
        if (idTexto == null || idTexto.isBlank()) {
            mostrar("⚠️ El campo ID está vacío. Escriba un número.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto.trim());
            mostrar("Consulta ID " + id + ":");
            mostrar(lista.consultarPorId(id));
        } catch (NumberFormatException e) {
            mostrar("⚠️ '" + idTexto.trim() + "' no es un ID válido. Use solo números.");
        }
    }//GEN-LAST:event_btnConsultarIdActionPerformed

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // ACTUALIZAR: Cambia el estado de "Pendiente" a "Revisada" buscando por ID
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            if (lista.actualizarEstado(id, "Revisada")) {
                mostrar("✅ ID " + id + " marcado como Revisada.");
            } else {
                mostrar("❌ ID " + id + " no encontrado.");
            }
        } catch (NumberFormatException e) {
            mostrar("Error: ingrese un ID numérico válido.");
        }
    }//GEN-LAST:event_btnRevisarActionPerformed

    private void btnEliminarUmbralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUmbralActionPerformed
        // ELIMINAR: Elimina alertas de Temperatura con valor menor al umbral
        try {
            float umbral    = Float.parseFloat(txtUmbral.getText().trim());
            int   eliminados = lista.eliminarAlertasMenoresA(umbral);
            mostrar("Se eliminaron " + eliminados + " alerta(s) de Temperatura < " + umbral + " °C.");
        } catch (NumberFormatException e) {
            mostrar("Error: ingrese un valor de umbral numérico válido.");
        }
    }//GEN-LAST:event_btnEliminarUmbralActionPerformed

    private void txtSensorBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSensorBuscarActionPerformed
        // Al presionar Enter en el campo sensor, ejecuta el filtrado
        btnFiltrarSensorActionPerformed(evt);
    }//GEN-LAST:event_txtSensorBuscarActionPerformed

    private void btnFiltrarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarSensorActionPerformed
        // CONSULTAR: Filtra todas las alertas de un SensorID específico
        String sensorId = txtSensorBuscar.getText();
        if (sensorId == null || sensorId.isBlank()) {
            mostrar("Error: ingrese un Sensor ID para filtrar.");
            return;
        }
        String alertas  = lista.filtrarPorSensor(sensorId);
        int    patrones = lista.contarPatronesSensor(sensorId);
        mostrar("--- ALERTAS DE " + sensorId + " ---");
        mostrar(alertas);
        mostrar("→ Alertas críticas en últimos 10 registros: " + patrones);
    }//GEN-LAST:event_btnFiltrarSensorActionPerformed

    private void txtUmbralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmbralActionPerformed
        // Al presionar Enter en el campo umbral, ejecuta la eliminación por umbral
        btnEliminarUmbralActionPerformed(evt);
    }//GEN-LAST:event_txtUmbralActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // ELIMINAR: Elimina una alerta por ID. La lista doble permite borrado O(1)
        // porque al encontrar el nodo, se accede a anterior y siguiente directamente.
        String idTexto = txtId.getText();
        if (idTexto == null || idTexto.isBlank()) {
            mostrar("⚠️ El campo ID está vacío. Escriba un número.");
            return;
        }
        try {
            int id = Integer.parseInt(idTexto.trim());
            if (lista.eliminarPorId(id)) {
                mostrar("✅ Registro ID " + id + " eliminado correctamente.");
            } else {
                mostrar("❌ ID " + id + " no encontrado. Use 'Listar Todas' para ver los IDs disponibles.");
            }
        } catch (NumberFormatException e) {
            mostrar("⚠️ '" + idTexto.trim() + "' no es un ID válido. Use solo números.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuParcial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextArea;
    private javax.swing.JButton btnCondensacion;
    private javax.swing.JButton btnConsultarId;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarUmbral;
    private javax.swing.JButton btnFiltrarSensor;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarInv;
    private javax.swing.JButton btnPeligroVib;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSensorBuscar;
    private javax.swing.JTextField txtSensorId;
    private javax.swing.JTextField txtUmbral;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
